# Source: kubernetes-ingress-controller/templates/agent-config-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-controller-kubernetes-ingress-controller-agent-cm
  namespace: #ngrok-namespace#
data:
  METADATA: ""
  REGION: ""
  REMOTE_MANAGEMENT: ""
---
# Source: kubernetes-ingress-controller/templates/controller-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-controller-kubernetes-ingress-controller-manager-config
  namespace: #ngrok-namespace#
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: ingress-controller-kubernetes-ingress-controller-leader