# Source: kubernetes-ingress-controller/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-controller-kubernetes-ingress-controller
  namespace: #ngrok-namespace#
  annotations:
    pulumi.com/patchForce: "true"
  labels:
    helm.sh/chart: kubernetes-ingress-controller-0.5.0
    app.kubernetes.io/name: kubernetes-ingress-controller
    app.kubernetes.io/instance: ingress-controller
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/part-of: kubernetes-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller