FROM apache/airflow:2.7.3-python3.9

# This is a dockerfile strictly for extra python packages for apache airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-discord==3.4.0 \
    apache-airflow-providers-github==2.4.0