apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
{{ include "rancher.labels" . | indent 4 }}
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "rancher.fullname" . }}
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ template "rancher.fullname" . }}
                port:
                  number: 80
  tls:
  - hosts:
    - nginx
