# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-httpsedge-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httpsedge-editor-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
---
# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-httpsedge-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httpsedge-viewer-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
---
# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-ippolicy-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ippolicy-editor-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
---
# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-ippolicy-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ippolicy-viewer-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
---
# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-tcpedge-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcpedge-editor-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
---
# Source: kubernetes-ingress-controller/templates/controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    pulumi.com/patchForce: "true"
  name: ngrok-ingress-controller-tcpedge-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tcpedge-viewer-role
subjects:
- kind: ServiceAccount
  name: ngrok-ingress-controller
  namespace: #ngrok-namespace#
